itvr-296-304-312--bcsc--dynamic-keycloak
bcgov/itvr pull request #135
Opened 2022-05-27 16:22 UTC by tim738745

(1) This replaces PR #127 (now closed); it appears that having multiple keycloaks initialized at the same time would cause the app to break (intermittently when only one keycloak was logged in, and completely when two keycloaks were logged in). Also, on Safari, the app would get into this infinite redirect loop immediately upon landing on the home page.

(2) Now, only one keycloak is initialized at a time, depending on what the user selects. The user's selection is persisted through redirects/refreshes using localStorage. Also, the app does not break if the user manages to log into both bceid and bcsc at the same time.

(3) I'm still not sure if this solution is ideal; what would be ideal is if the bceid and bcsc idps are both in the same keycloak realm; if this is not possible from a security standpoint, this video (https://www.youtube.com/watch?v=lJlKNmAsaiE) suggests using subdomains to determine which keycloak to use. For example, we would have bcsc.goelectric.ca, and bceid.goelectric.ca. However, this would involve UI redesigns and possibly need to coordinate with the people designing the "go electric" website that will point to our app...

2022-05-27 18:19 UTC, naomiaro requested changes
Hopefully the two keycloak realms will just be temporary for a few months and bcsc is in the common hosted realm soon. Besides just setting up a separate client for itvr, and then giving a list of env vars to Kuan, lgtm 😄

2022-05-27 18:19 UTC, naomiaro commented on keycloak.env
> +BCSC_KEYCLOAK_CLIENT_ID=zeva
This should still have a separate itvr client setup.

2022-05-27 18:19 UTC, naomiaro commented on frontend/src/index.js
> +}
maybe this keycloak check can be moved into `./keycloak`?

2022-05-27 20:53 UTC, tim738745 commented
@naomiaro I made the changes, setup a new itvr client in the rzh2zkjq realm, and gave Kuan the new env vars; should be good now!

2022-05-30 16:23 UTC, naomiaro approved these changes

2022-05-30 16:23 UTC, merged