Metadata and fav-icon
bcgov/itvr pull request #137
Opened 2022-05-29 22:26 UTC by vibhiquartech

https://apps.nrs.gov.bc.ca/int/jira/browse/CTHUB-298

2022-05-30 16:27 UTC, naomiaro commented
Sorry @vibhiquartech I just merged some PRs, that must have caused another conflict here

2022-05-30 20:37 UTC, naomiaro requested changes
needs rebase

2022-05-31 16:02 UTC, naomiaro commented
Since Sonarcloud is complaining about duplication here: https://github.com/nfl/react-helmet#reference-guide let's look into using nested templates and `titleTemplate`

2022-05-31 16:04 UTC, naomiaro commented
This also needs another rebase to not `pick` commits by Kuan and Tim. They are already merged into the main branch.

2022-05-31 16:07 UTC, vibhiquartech commented
Do you suggest i should fetch upstream and rebase to my fork as i have previously rebased to the bcgov/release-1.1.0?
________________________________
From: Naomi ***@***.***>
Sent: Tuesday, May 31, 2022 9:05 AM
To: bcgov/itvr ***@***.***>
Cc: Vel, Vibhishan ***@***.***>; Mention ***@***.***>
Subject: Re: [bcgov/itvr] Metadata and fav-icon (PR #137)

CAUTION: This email originated from outside of Quartech. Do not click links or open attachments unless you recognize the sender and know the content is safe.


This also needs another rebase to not pick commits by Kuan and Tim. They are already merged into the main branch.

—
Reply to this email directly, view it on GitHub<https://github.com/bcgov/itvr/pull/137#issuecomment-1142327268>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZDKW5UBJVPDE2AZZ7QUCODVMY2DNANCNFSM5XIZI6MA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-05-31 20:58 UTC, naomiaro commented
Just going to merge with duplication for now since I think part of the problem is that we're reusing page titles.

2022-05-31 20:59 UTC, naomiaro commented
Hmm but now I see that only administrators will be allowed to merge if I do this.

2022-05-31 22:19 UTC, naomiaro requested changes

2022-05-31 22:19 UTC, naomiaro commented on frontend/src/pages/HouseholdForm.js
> +      Hello BCeID {decoded.preferred_username}
@vibhiquartech I think this decoded part might have been from the rebase, this variable doesn't exist anymore

2022-06-01 16:39 UTC, closed without merging