cthub-247--frontend-validation
bcgov/itvr pull request #77
Opened 2022-04-19 15:18 UTC by tim738745

2022-04-26 17:08 UTC, naomiaro requested changes
Are you using Vscode @tim738745 ? If you install the `prettier` extension the code formatting should format on save.

2022-04-26 17:11 UTC, tim738745 commented on frontend/src/components/Form.js
>                  inputProps={{ maxLength: 9 }}
Sure; and yes I am using vscode; will install prettier.

2022-04-27 16:34 UTC, naomiaro commented
@tim738745 you'll have to rebase this branch off the upstream release 1.0.0 so that it can be merged.

2022-04-27 17:22 UTC, tim738745 commented
@naomiaro I think I rebased correctly

2022-04-27 20:16 UTC, naomiaro commented
hmm this should only have commits from yourself and not Kuan etc. Usually it will require a force push to the PR as the history will be rewritten.

2022-04-27 20:21 UTC, tim738745 commented
ohh after I rebased and tried to push vscode wanted me to pull stuff into my branch which I did instead of force pushing...let me see if I can fix this

2022-04-27 20:22 UTC, naomiaro commented
Yeah the vscode UI might pull by merging, I don't usually use vscode so I'm not sure. In the terminal you can use `git pull --rebase` to pull changes into a branch.

2022-04-27 21:28 UTC, tim738745 commented
ok it should be good now

2022-04-27 21:33 UTC, naomiaro approved these changes

2022-04-27 21:33 UTC, merged